### ISSUE TITLE
Ajout de la même vidéo plusieurs fois

### ISSUE THREAD

**Issue by oliviermeunier** [lauralazzaro/snowtricks#24]
A chaque fois que je valida le formulaire de modification d'une figure, les vidéos présentes sont à nouveau insérer dans la base de données : 
![image](https://user-images.githubusercontent.com/5786996/190996577-7618ed0c-6f35-43be-90a6-d961f6309558.png)

**Comment by lauralazzaro** [comment]
Cannot reproduce. Fixed when added a redirect after updating the trick
