### ISSUE TITLE
Reset password expiration

### ISSUE THREAD

**Issue by oliviermeunier** [lauralazzaro/snowtricks#25]
Il est indiqué que le lien de réinitialisation du mot de passe est valide 0 minutes. Cela fonctionne bien, c'est juste le message avec le nombre de minutes qui est incorrect. 
![image](https://user-images.githubusercontent.com/5786996/190997102-3a84e88e-2abe-4c1b-967b-14afa8dc088b.png)

**Comment by lauralazzaro** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/9378494/191077515-18a70f65-de43-45f2-890c-361e0b4ddaf9.png)
![image](https://user-images.githubusercontent.com/9378494/191077574-f3958a53-93b2-45c8-bd18-d5be71367af4.png)
